name: "Terraform"

on:
  push:
    branches:
      - dev1

env:
    AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID  }}    # set this to your Azure Subscription Id
    AZURE_WEBAPP_PACKAGE_PATH: ./app/Deploy6.zip
    AZURE_WEBAPP_NAME: wappeu2fabsd01
    AZURE_WEBAPP_SLOT_NAME: app-release
    AZURE_RESOURCE_GROUP: rsgreu2fabsd01
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
  Webappdeploy:
    name: "Webappdeploy"
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 60 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Run Azure webapp deploy action'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
          package:  ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: Azure Swap Slots
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp deployment slot swap --slot ${{ env.AZURE_WEBAPP_SLOT_NAME }} --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}